"""soft_delete_partial_index

Revision ID: 3e34fb4b2802
Revises: 8851e5d53d5f
Create Date: 2026-02-13 13:24:26.381871
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e34fb4b2802'
down_revision: Union[str, None] = '8851e5d53d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('id_migration_map_old_user_id_key', 'id_migration_map', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index('ix_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_unique_constraint('id_migration_map_old_user_id_key', 'id_migration_map', ['old_user_id'])
    # ### end Alembic commands ###
