"""allow_duplicate_role_names_and_add_user_doj

Revision ID: 5cbf1e02c983
Revises: 463f1b6000e9
Create Date: 2026-02-13 10:27:11.292815
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cbf1e02c983'
down_revision: Union[str, None] = '463f1b6000e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index('ix_roles_name_active', 'roles', ['name'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.add_column('users', sa.Column('date_of_joining', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_joining')
    op.drop_index('ix_roles_name_active', table_name='roles', postgresql_where=sa.text('is_active IS true'))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
