"""Add version column to users and roles

Revision ID: 463f1b6000e9
Revises: 
Create Date: 2026-02-13 10:17:34.163370
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463f1b6000e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add columns as nullable first
    op.add_column('roles', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('version', sa.Integer(), nullable=True))
    
    # 2. Populate existing rows with default version 1
    op.execute("UPDATE roles SET version = 1")
    op.execute("UPDATE users SET version = 1")
    
    # 3. Alter columns to be non-nullable
    op.alter_column('roles', 'version', nullable=False)
    op.alter_column('users', 'version', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'version')
    op.drop_column('roles', 'version')
    # ### end Alembic commands ###
