"""migrate_to_ulid

Revision ID: 8851e5d53d5f
Revises: 0ba12bbebd03
Create Date: 2026-02-13 13:13:11.600855
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8851e5d53d5f'
down_revision: Union[str, None] = '0ba12bbebd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversion_history', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('conversion_history', sa.Column('user_ulid', sa.String(length=26), nullable=False))
    op.add_column('conversion_history', sa.Column('previous_category', sa.String(length=20), nullable=False))
    op.add_column('conversion_history', sa.Column('new_category', sa.String(length=20), nullable=False))
    op.drop_constraint('conversion_history_intern_user_id_fkey', 'conversion_history', type_='foreignkey')
    op.create_foreign_key(None, 'conversion_history', 'users', ['user_id'], ['id'])
    op.drop_column('conversion_history', 'previous_user_id')
    op.drop_column('conversion_history', 'intern_user_id')
    op.drop_column('conversion_history', 'new_user_id')
    op.add_column('users', sa.Column('ulid', sa.String(length=26), nullable=False))
    op.drop_index('ix_users_user_id', table_name='users')
    op.create_index(op.f('ix_users_ulid'), 'users', ['ulid'], unique=True)
    op.create_index('ix_users_ulid_suffix', 'users', ['ulid'], unique=False)
    op.drop_column('users', 'previous_id')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('previous_id', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_index('ix_users_ulid_suffix', table_name='users')
    op.drop_index(op.f('ix_users_ulid'), table_name='users')
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=True)
    op.drop_column('users', 'ulid')
    op.add_column('conversion_history', sa.Column('new_user_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('conversion_history', sa.Column('intern_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('conversion_history', sa.Column('previous_user_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversion_history', type_='foreignkey')
    op.create_foreign_key('conversion_history_intern_user_id_fkey', 'conversion_history', 'users', ['intern_user_id'], ['id'])
    op.drop_column('conversion_history', 'new_category')
    op.drop_column('conversion_history', 'previous_category')
    op.drop_column('conversion_history', 'user_ulid')
    op.drop_column('conversion_history', 'user_id')
    # ### end Alembic commands ###
